import {
  AirTravelFrequency,
  BroadcastChannel,
  DigitalIntensity,
  HeatSource,
  MeatFrequency,
  PurchasingStrategy,
  TransportationMode,
} from "@prisma/client";

export const getValideCarbonFootprintPayload = (
  surveyName: string,
  su?: number,
  knowSu?: boolean,
) => ({
  id: "48c791b5-4d1c-4146-b92d-4f9f6e84ce81",
  broadcastChannel: BroadcastChannel.qr_code,
  calculatedResults: {
    bilan: 8102.619815057512,
    transport: 1160.7971411728793,
    "transport . voiture": 770.8627820342634,
    "transport . voiture . km2": 125,
    "transport . voiture . thermique . consommation aux 100": 125,
    "transport . voiture . thermique . carburant": 125,
    "transport . voiture . électrique . consommation aux 100": 125,
    "transport . avion": 312.2395338291978,
    "transport . deux roues": 23.196418035061875,
    "transport . mobilité douce": 0,
    "transport . train": 8.8198802395209,
    "transport . transports commun": 33.7904763482199,
    "transport . car longue distance": 125,
    "transport . vacances": 0,
    "transport . vacances . caravane": 125,
    "transport . vacances . camping car": 125,
    "transport . vacances . van": 125,
    "transport . vacances . location véhicule ": 125,
    "transport . vacances . croisière": 125,
    "transport . ferry": 11.88805068661542,
    alimentation: 2339.1671821,
    "alimentation . repas": 1908.8380000000002,
    "alimentation . déjeuner et dîner": 1585.688,
    "alimentation . bonus": 0,
    "alimentation . local . empreinte": 0,
    "alimentation . local . consommation": 125,
    "alimentation . de saison . empreinte": 0,
    "alimentation . petit déjeuner annuel": 113.15,
    "alimentation . déforestation": 210,
    "alimentation . boisson": 235.8398,
    "alimentation . boisson . chaude": 56.3998,
    "alimentation . boisson . froide": 179.44,
    "alimentation . déchets": 194.4893821,
    "alimentation . déchets . gestes": 125,
    logement: 2160.200464307907,
    "logement . construction": 968.7934897866139,
    "logement . construction . base": 9.2,
    "logement . construction . rafraichissement": 4,
    "logement . construction . rénovation": 9.4,
    "logement . construction . déforestation": 0.8974091460882545,
    "logement . construction . artificialisation sols": 125,
    "logement . électricité": 132.21789018483327,
    "logement . électricité . consommation totale": 5593.833815512177,
    "logement . électricité . photovoltaique . autoconsommation": 125,
    "logement . électricité . intensité carbone équivalente": 0.052,
    "logement . chauffage": 822.4772605840475,
    "logement . climatisation": 63.176259272727265,
    "logement . piscine": 125,
    "logement . extérieur": 21.45057795454545,
    "logement . vacances": 152.08498652513995,
    "logement . vacances . empreinte hotel": 125,
    "logement . vacances . empreinte camping": 125,
    "logement . vacances . empreinte auberge de jeunesse": 125,
    "logement . vacances . empreinte locations": 125,
    "logement . vacances . empreinte échange": 125,
    "logement . vacances . empreinte résidence secondaire": 125,
    divers: 991.5498010903609,
    "divers . électroménager": 75.44090909090907,
    "divers . électroménager . appareils": 165.96999999999997,
    "divers . ameublement": 139.7448484848485,
    "divers . ameublement . meubles": 185.93866666666668,
    "divers . ameublement . déforestation": 121.5,
    "divers . ameublement . préservation": 125,
    "divers . numérique": 120.076661030303,
    "divers . numérique . internet": 3.3613579999999996,
    "divers . numérique . appareils": 116.715303030303,
    "divers . textile": 327.79344827586203,
    "services sociétaux": 1450.9052263863641,
    "services publics": 125,
    "services marchands": 125,
  },
  answers: {
    broadcastChannel: BroadcastChannel.qr_code, // near-47 to confirm
    neighborhood: surveyName, // near-47 to confirm
    knowSu: knowSu ?? false, // near-47 to confirm
    su, // near-47 to confirm
    meatFrequency: MeatFrequency.MAJOR, // near-47 to confirm
    transportationMode: TransportationMode.CAR, // near-47 to confirm
    purchasingStrategy: PurchasingStrategy.MIXED, // near-47 to confirm
    airTravelFrequency: AirTravelFrequency.ABOVE_3, // near-47 to confirm
    heatSource: HeatSource.ELECTRICITY, // near-47 to confirm
    digitalIntensity: DigitalIntensity.INTENSE, // near-47 to confirm
    userAnswers: {
      "transport . voiture . utilisateur": "je ne sais pas",
      "transport . voiture . km": 2080,
      "transport . voiture . voyageurs": 1,
      "transport . avion . usager": "je ne sais pas",
      "transport . deux roues . usager": "je ne sais pas",
      "transport . mobilité douce . marche . présent": "je ne sais pas",
      "transport . mobilité douce . vélo . présent": "je ne sais pas",
      "transport . mobilité douce . vae . présent": "je ne sais pas",
      "transport . mobilité douce . autres véhicules à moteur . présent":
        "je ne sais pas",
      "transport . train . km": "je ne sais pas",
      "transport . transports commun . bus . présent": "je ne sais pas",
      "transport . transports commun . car . présent": "je ne sais pas",
      "transport . transports commun . métro ou tram . présent":
        "je ne sais pas",
      "transport . vacances . camping car . propriétaire": "je ne sais pas",
      "transport . vacances . caravane . propriétaire": "je ne sais pas",
      "transport . vacances . van . propriétaire": "je ne sais pas",
      "transport . ferry . usager": "je ne sais pas",
      "alimentation . plats . végétalien . nombre": "je ne sais pas",
      "alimentation . plats . viande rouge . nombre": "je ne sais pas",
      "alimentation . plats . viande blanche . nombre": "je ne sais pas",
      "alimentation . plats . végétarien . nombre": "je ne sais pas",
      "alimentation . plats . poisson gras . nombre": "je ne sais pas",
      "alimentation . plats . poisson blanc . nombre": "je ne sais pas",
      "alimentation . local . consommation": "je ne sais pas",
      "alimentation . de saison . consommation": "je ne sais pas",
      "alimentation . petit déjeuner . type": "je ne sais pas",
      "alimentation . boisson . chaude . café . nombre": "je ne sais pas",
      "alimentation . boisson . chaude . thé . nombre": "je ne sais pas",
      "alimentation . boisson . chaude . chocolat chaud . nombre":
        "je ne sais pas",
      "alimentation . boisson . chaude . chicorée . nombre": "je ne sais pas",
      "alimentation . boisson . sucrées . litres": "je ne sais pas",
      "alimentation . boisson . alcool . litres": "je ne sais pas",
      "alimentation . boisson . eau en bouteille . consommateur":
        "je ne sais pas",
      "alimentation . déchets . quantité jetée": "je ne sais pas",
      "logement . habitants": "je ne sais pas",
      "logement . surface": "je ne sais pas",
      "logement . type": "je ne sais pas",
      "logement . âge": "je ne sais pas",
      "logement . construction . rénovation . travaux . rénovation . présent":
        "je ne sais pas",
      "logement . construction . rénovation . travaux . isolation . présent":
        "je ne sais pas",
      "logement . construction . rénovation . travaux . chauffage . présent":
        "je ne sais pas",
      "logement . construction . rénovation . travaux . extension . présent":
        "je ne sais pas",
      "logement . électricité . réseau . consommation": "je ne sais pas",
      "logement . électricité . photovoltaique . présent": "je ne sais pas",
      "logement . chauffage . PAC . présent": "je ne sais pas",
      "logement . chauffage . électricité . présent": "je ne sais pas",
      "logement . chauffage . gaz . présent": "je ne sais pas",
      "logement . chauffage . réseau de chaleur . présent": "je ne sais pas",
      "logement . chauffage . bouteille gaz . présent": "je ne sais pas",
      "logement . chauffage . citerne propane . présent": "je ne sais pas",
      "logement . chauffage . fioul . présent": "je ne sais pas",
      "logement . chauffage . bois . présent": "je ne sais pas",
      "logement . chauffage . bois . type": "je ne sais pas",
      "logement . climatisation . présent": "je ne sais pas",
      "logement . vacances . hotel . présent": "je ne sais pas",
      "logement . vacances . camping . présent": "je ne sais pas",
      "logement . vacances . auberge de jeunesse . présent": "je ne sais pas",
      "logement . vacances . locations . présent": "je ne sais pas",
      "logement . vacances . échange . présent": "je ne sais pas",
      "logement . vacances . famille ou amis . présent": "je ne sais pas",
      "logement . vacances . résidence secondaire . présent": "je ne sais pas",
      "divers . électroménager . appareils . réfrigérateur . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . petit réfrigérateur . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . congélateur . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . lave-linge . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . sèche-linge . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . lave-vaisselle . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . four . nombre": "je ne sais pas",
      "divers . électroménager . appareils . micro-onde . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . plaques . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . hotte . nombre": "je ne sais pas",
      "divers . électroménager . appareils . bouilloire . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . cafetière . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . aspirateur . nombre":
        "je ne sais pas",
      "divers . électroménager . appareils . robot cuisine . nombre":
        "je ne sais pas",
      "divers . ameublement . meubles . armoire . nombre": "je ne sais pas",
      "divers . ameublement . meubles . canapé . nombre": "je ne sais pas",
      "divers . ameublement . meubles . matelas . nombre": "je ne sais pas",
      "divers . ameublement . meubles . lit . nombre": "je ne sais pas",
      "divers . ameublement . meubles . table . nombre": "je ne sais pas",
      "divers . ameublement . meubles . chaise . nombre": "je ne sais pas",
      "divers . ameublement . meubles . petit meuble . nombre":
        "je ne sais pas",
      "divers . numérique . internet . durée journalière": "je ne sais pas",
      "divers . numérique . appareils . téléphone . nombre": "je ne sais pas",
      "divers . numérique . appareils . TV . nombre": "je ne sais pas",
      "divers . numérique . appareils . ordinateur portable . nombre":
        "je ne sais pas",
      "divers . numérique . appareils . ordinateur fixe . nombre":
        "je ne sais pas",
      "divers . numérique . appareils . tablette . nombre": "je ne sais pas",
      "divers . numérique . appareils . enceinte bluetooth . nombre":
        "je ne sais pas",
      "divers . numérique . appareils . console de salon . nombre":
        "je ne sais pas",
      "divers . numérique . appareils . console portable . nombre":
        "je ne sais pas",
      "divers . textile . chaussure . nombre": "je ne sais pas",
      "divers . textile . petit article . nombre": "je ne sais pas",
      "divers . textile . gros article . nombre": "je ne sais pas",
      "divers . produits consommables . consommation": "je ne sais pas",
      "divers . autres produits . niveau de dépenses": "je ne sais pas",
    },
    voitures: [
      {
        id: "11a6f43c-513c-41c3-8ec1-62a5019e2f4c",
        label: "holidays",
        distance: 10,
        reccurrence: 1,
        period: "week",
        passengers: 1,
      },
      {
        id: "3c84fd98-57b9-444b-b327-f86a50b67cbe",
        label: "holidays",
        distance: 10,
        reccurrence: 1,
        period: "week",
        passengers: 1,
      },
      {
        id: "e87e099d-b47e-4b54-8c57-14143b8b0e8b",
        label: "holidays",
        distance: 10,
        reccurrence: 1,
        period: "week",
        passengers: 1,
      },
      {
        id: "0c41725b-ba25-4425-9125-31a361498c68",
        label: "holidays",
        distance: 10,
        reccurrence: 1,
        period: "week",
        passengers: 1,
      },
    ],
  },
});
