import { BroadcastChannel } from "@prisma/client";
import { env } from "~/env";

// If you need to update use data generated by typeform test hook
export const valideSuSurveyPayload = {
  event_id: "01JKAV3QZY91SNR0X3A7MNE77D",
  event_type: "form_response",
  form_response: {
    form_id: env.SU_FORM_ID,
    token: "gleti7pkz8gj5ez0gleupepebwmypwe5",
    landed_at: "2025-02-05T10:39:52Z",
    submitted_at: "2025-02-05T10:39:52Z",
    hidden: {
      neighborhood: "name",
      broadcast_channel: BroadcastChannel.mail_campaign,
      broadcast_id: "de68a7fa-35a8-441d-97ee-05f0c64d634b",
    },
    definition: {
      id: env.SU_FORM_ID,
      title: "Sphères d'Usages V1.92 (copie test)",
      fields: [
        {
          id: "oUXuhFxx8N00",
          ref: "isNeighborhoodResident",
          type: "multiple_choice",
          title: "🏙️📍 Vivez-vous dans le quartier [nom du quartier] ?",
          properties: {},
          choices: [
            {
              id: "Iw7sUEnnQOW1",
              ref: "6226e10f-baf0-43f8-af05-2cddc649f509",
              label: "Oui (j'y habite ou j'y suis souvent)",
            },
            {
              id: "fugWMOloSfDA",
              ref: "3a347ad6-7461-4549-8cf3-d45167702a74",
              label: "Non",
            },
          ],
        },
        {
          id: "JwT4jf99PqwZ",
          ref: "ageCategory",
          type: "multiple_choice",
          title: "🧒🧓 Dans quelle tranche d’âge vous trouvez-vous ? ",
          properties: {},
          choices: [
            {
              id: "quEgbNpyxmlD",
              ref: "a403515c-5a86-4c4b-a842-bae699a09f47",
              label: "Moins de 15 ans",
            },
            {
              id: "46nXytjeqV4c",
              ref: "e56029c8-f14a-45dc-8a90-4e61a0f45581",
              label: "15 à 29 ans",
            },
            {
              id: "MGN8iiCc82cx",
              ref: "58756e59-7741-4e9b-8d7b-c16c8eca4361",
              label: "30 à 44 ans",
            },
            {
              id: "2VrLQOyMxY85",
              ref: "e1d0ef1b-5caa-4b62-aed0-f8efa82131b3",
              label: "45 à 59 ans",
            },
            {
              id: "RXS0N3PyMEif",
              ref: "65b4afe2-e818-456e-b9fe-a5082a9abc79",
              label: "60 à 74 ans",
            },
            {
              id: "SBSp9JHSIeA5",
              ref: "fa4746bb-223c-4bbc-8a39-ff07a2246a0b",
              label: "75 ans et plus",
            },
          ],
        },
        {
          id: "z8pS3bYvL4fk",
          ref: "gender",
          type: "multiple_choice",
          title: "♀️♂️ Quel est votre genre ? ",
          properties: {},
          choices: [
            {
              id: "OVajhTciqVz5",
              ref: "191de28b-587d-4f34-b57f-b687c77e1c1e",
              label: "Femme",
            },
            {
              id: "V538CoGJs48v",
              ref: "1caec0f3-6a02-42e6-9bf7-10030b6d38b6",
              label: "Homme",
            },
            {
              id: "BZ85rcdhgijl",
              ref: "9ac0fb83-a344-44d4-a235-add149bb6de3",
              label: "Autre",
            },
          ],
        },
        {
          id: "ZKmXP3TwmEm5",
          ref: "professionalCategory",
          type: "multiple_choice",
          title: "👷‍♀️👨‍⚖️ Quelle est votre catégorie socio-professionnelle ?* *",
          properties: {},
          choices: [
            {
              id: "7gUWDN5CbRUZ",
              ref: "34937a02-6445-4624-9d37-06158160fedc",
              label: "*Agriculteurs exploitant*",
            },
            {
              id: "Hu4N1RyzVMqB",
              ref: "eafa75de-50ee-42b5-8a49-9edc5a665d5c",
              label: "*Artisans, commerçants et chefs d'entreprise*",
            },
            {
              id: "SAKNBtjP3iqK",
              ref: "a69d126e-0436-4b3d-b1b7-ba39af69354f",
              label:
                "*Cadre et professions intellectuelles supérieures* (avocats, architectes, médecins, professeurs, scientifiques, …)",
            },
            {
              id: "Yika7Njb6ZhK",
              ref: "d8ff03ac-c2e7-4db7-a4ba-dd1162d31d0d",
              label:
                "*Professions intermédiaires* (santé, social, enseignement, techniciens, agents de maîtrise, employés qualifiés, …)",
            },
            {
              id: "n3BlsM8GxwqN",
              ref: "1f383874-b1ba-4b95-84ca-5bb735afb1f3",
              label: "*Employés*",
            },
            {
              id: "WEFGZWPCauh7",
              ref: "1af27fdf-88ac-4a0c-ae42-3961c1509763",
              label:
                "*Ouvriers *(qualifiés (industrie, bâtiment, transport, etc.) et non-qualifiés (manœuvres, manutentions, etc.), conducteurs, chauffeurs).",
            },
            {
              id: "l2iwR15MS5xI",
              ref: "144ee3b6-cc45-4c8a-bd6b-d507579a8a27",
              label: "*Retraités*",
            },
            {
              id: "toF2Sdi83jmB",
              ref: "c72b89cf-162b-422c-a55c-cd831494fcfb",
              label:
                "*Autre personnes sans activité professionnelle *(chômeur, rentiers)",
            },
            {
              id: "tidKRdys8El1",
              ref: "a18b427c-ab45-4534-ad45-326c142a7869",
              label: "*Étudiants et/ou stagiaires*",
            },
          ],
        },
        {
          id: "8OiuZK8vWvXN",
          ref: "easyHealthAccess",
          type: "multiple_choice",
          title:
            "⚕️💶 Est-ce qu’il est aisé pour vous de financer votre accès aux soins ?",
          properties: {},
          choices: [
            {
              id: "QZYsk2rDUcvT",
              ref: "2360d7d5-b501-4f3e-b829-4b374483849e",
              label:
                "*Pas de limitation forte vis-à-vis du coût des soins de base ou de soins spécialisés.* Vous n'avez pas de problème pour accéder à tous les types de soin, y compris spécialisés et coûteux.",
            },
            {
              id: "G7M6Me72ui8N",
              ref: "bd25627f-8aa4-4c43-a013-635e5af4cee0",
              label:
                "*Les soins de base sont faciles à obtenir, mais les soins spécialisés sont difficiles à financer.* Vous avez un accès satisfaisant aux soins de base, mais les soins plus coûteux ou spécialisés nécessitent des efforts financiers importants.",
            },
            {
              id: "jR33YoOKpdKg",
              ref: "9fe68244-2af7-49a0-a9e1-7d5e73878953",
              label:
                "*Les soins de base comme les soins spécialisés sont difficiles à financer. *L'accès aux soins est régulièrement limité par des contraintes financières",
            },
          ],
        },
        {
          id: "dZltG3fKIYO4",
          ref: "meatFrequency",
          type: "multiple_choice",
          title:
            "🍖🥓 Lors de vos repas, la viande (poulet, bœuf, etc…) est présente dans… ",
          properties: {},
          choices: [
            {
              id: "0xaNJ1uzjLZD",
              ref: "3beb39cf-2cee-4c3b-81fb-8dd1b1ea3f00",
              label: "0 à 4 repas par semaine (rarement ou jamais)",
            },
            {
              id: "KVGZULXscGsT",
              ref: "f3d254c4-0b61-4aa4-9df4-a631475787d6",
              label: "5 à 9 repas par semaine (régulièrement)",
            },
            {
              id: "dJbIS3pECKby",
              ref: "6884a62e-bc9f-47af-8e28-7ea4a27f0230",
              label: "10 repas par semaine ou plus (majoritairement)",
            },
          ],
        },
        {
          id: "8qh4vbXKaCop",
          ref: "transportationMode",
          type: "multiple_choice",
          title:
            "🚗🚲 Quel mode de transport utilisez-vous le plus pour vos déplacements réguliers ?",
          properties: {},
          choices: [
            {
              id: "EZWReHWBbvTN",
              ref: "8719d78b-30c6-4ef4-b7c4-a4627f594502",
              label: "Voiture",
            },
            {
              id: "tsJEndtJtcdD",
              ref: "45402959-78d9-4518-b3c3-ab5d3e4c1feb",
              label: "Transports en commun",
            },
            {
              id: "iqCslFz9EHdN",
              ref: "7612df4d-5cb3-484c-8026-030331c61b3a",
              label: "Vélo, trottinette ou marche",
            },
          ],
        },
        {
          id: "JxtcOM50Qm0e",
          ref: "digitalIntensity",
          type: "multiple_choice",
          title:
            "🤳💻 Quelle est l’intensité de votre utilisation du numérique (téléphone, ordinateur, TV, …) ?",
          properties: {},
          choices: [
            {
              id: "j94LA9hOHHfv",
              ref: "270e40f2-2aa5-43b2-b9d9-0cadd018442c",
              label:
                "*Utilisation légère* (mails, bureautique, un peu de streaming ou jeux vidéo, *moins de 2h par jour*)",
            },
            {
              id: "sazWrDTRoENb",
              ref: "8b1e124f-a5d2-4a02-9383-3ef0e5aa7cf9",
              label:
                "*Utilisation régulière* (Usage varié avec *entre 2 et 4 heures* de streaming quotidien, de jeux vidéo (console ou mobile), ou de télévision).",
            },
            {
              id: "QmMvmuE2dHkV",
              ref: "f04dfe0c-f517-403e-883a-bb8c9de80de8",
              label:
                "*Utilisation intensive* (Usage intensif avec *plus de 4 heures par jour *consacrées au streaming vidéo, aux jeux vidéo ou à la télévision).",
            },
          ],
        },
        {
          id: "Dpl4qNCPtGVV",
          ref: "purchasingStrategy",
          type: "multiple_choice",
          title:
            "🛒💶 Quand vous avez besoin d’un objet (vêtements, électronique, mobilier, …), vous privilégiez généralement…",
          properties: {},
          choices: [
            {
              id: "dsg572gscKgo",
              ref: "84702054-4b2e-40c9-932a-3bd813d5d646",
              label:
                "…*le neuf en priorité* (même si l'occasion est disponible)",
            },
            {
              id: "GhW9lybgoeo6",
              ref: "13c4b137-28c3-4cca-ae27-6b228fb52f37",
              label:
                "…*un mélange entre neuf et occasion* (selon la disponibilité ou le type de produit)",
            },
            {
              id: "vrm1jGyAaxDu",
              ref: "8166cf94-e353-4b46-a522-acd9530782c0",
              label:
                "…*l’occasion en priorité *(neuf seulement en dernier recours)",
            },
          ],
        },
        {
          id: "HreBEMDifVhr",
          ref: "airTravelFrequency",
          type: "multiple_choice",
          title:
            "🛫👩‍✈️ En moyenne, combien d’allers-retours en avion faites-vous par an ?",
          properties: {},
          choices: [
            {
              id: "TJaIV97Vek20",
              ref: "22c056f4-21e7-4e63-8fb6-60b1f5569f8b",
              label: "*0*",
            },
            {
              id: "r2JDDCClqtMC",
              ref: "e9c48d61-16c8-41a4-a53e-e8d838c539be",
              label: "*1 à 3 allers-retours*",
            },
            {
              id: "eDWfhTDTko6k",
              ref: "04385aba-ae3e-4bda-b32b-1f0c03bec5b8",
              label: "*Plus de 3 allers-retours*",
            },
          ],
        },
        {
          id: "rOBkR1gVgkyP",
          ref: "heatSource",
          type: "multiple_choice",
          title: "♨️🏠 Quelle est l’énergie de chauffage de votre logement ?",
          properties: {},
          choices: [
            {
              id: "pt9lOL1L8zvk",
              ref: "6a3d2558-6612-4cf1-90a6-e5e1bf3bbca8",
              label: "*Électricité, réseau de chaleur ou pompe à chaleur*",
            },
            {
              id: "RjztaRJTDdpG",
              ref: "60220a76-eacb-435d-beb9-30c6e139827c",
              label: "*Gaz*",
            },
            {
              id: "MvpSO8T9i1gU",
              ref: "8d91547d-f2aa-4987-9d0b-cb3ce17527c5",
              label: "*Fioul*",
            },
          ],
        },
        {
          id: "wldBg2PVYBgI",
          ref: "email",
          type: "email",
          title:
            "📧🤚 *Souhaitez-vous nous transmettre votre mail pour être tenu au courant des résultats ?*",
          properties: {},
        },
      ],
      endings: [
        {
          id: "OEYROGkSgGg3",
          ref: "9acf61d6-becd-4a62-bea3-4353c07d5769",
          title: "Vous ne faites pas partie du public de cette enquête. ",
          type: "thankyou_screen",
          properties: {
            description:
              "Vous pouvez cependant nous aider à la diffuser aux personnes de plus de 15 ans, habitants ou visiteurs réguliers du quartier.",
            button_text: "Create a typeform",
            show_button: true,
            share_icons: true,
            button_mode: "default_redirect",
          },
        },
      ],
    },
    answers: [
      {
        type: "choice",
        choice: {
          id: "Iw7sUEnnQOW1",
          label: "Oui (j'y habite ou j'y suis souvent)",
          ref: "6226e10f-baf0-43f8-af05-2cddc649f509",
        },
        field: {
          id: "oUXuhFxx8N00",
          type: "multiple_choice",
          ref: "isNeighborhoodResident",
        },
      },
      {
        type: "choice",
        choice: {
          id: "46nXytjeqV4c",
          label: "15 à 19 ans",
          ref: "e56029c8-f14a-45dc-8a90-4e61a0f45581",
        },
        field: {
          id: "JwT4jf99PqwZ",
          type: "multiple_choice",
          ref: "ageCategory",
        },
      },
      {
        type: "choice",
        choice: {
          id: "OVajhTciqVz5",
          label: "Femme",
          ref: "191de28b-587d-4f34-b57f-b687c77e1c1e",
        },
        field: {
          id: "z8pS3bYvL4fk",
          type: "multiple_choice",
          ref: "gender",
        },
      },
      {
        type: "choice",
        choice: {
          id: "7gUWDN5CbRUZ",
          label: "*Agriculteurs exploitant*",
          ref: "34937a02-6445-4624-9d37-06158160fedc",
        },
        field: {
          id: "ZKmXP3TwmEm5",
          type: "multiple_choice",
          ref: "professionalCategory",
        },
      },
      {
        type: "choice",
        choice: {
          id: "QZYsk2rDUcvT",
          label:
            "*Pas de limitation forte vis-à-vis du coût des soins de base ou de soins spécialisés.* Vous n'avez pas de problème pour accéder à tous les types de soin, y compris spécialisés et coûteux.",
          ref: "2360d7d5-b501-4f3e-b829-4b374483849e",
        },
        field: {
          id: "8OiuZK8vWvXN",
          type: "multiple_choice",
          ref: "easyHealthAccess",
        },
      },
      {
        type: "choice",
        choice: {
          id: "0xaNJ1uzjLZD",
          label: "0 à 4 repas par semaine (rarement ou jamais)",
          ref: "3beb39cf-2cee-4c3b-81fb-8dd1b1ea3f00",
        },
        field: {
          id: "dZltG3fKIYO4",
          type: "multiple_choice",
          ref: "meatFrequency",
        },
      },
      {
        type: "choice",
        choice: {
          id: "EZWReHWBbvTN",
          label: "Voiture",
          ref: "8719d78b-30c6-4ef4-b7c4-a4627f594502",
        },
        field: {
          id: "8qh4vbXKaCop",
          type: "multiple_choice",
          ref: "transportationMode",
        },
      },
      {
        type: "choice",
        choice: {
          id: "j94LA9hOHHfv",
          label:
            "*Utilisation légère* (mails, bureautique, un peu de streaming ou jeux vidéo, *moins de 2h par jour*)",
          ref: "270e40f2-2aa5-43b2-b9d9-0cadd018442c",
        },
        field: {
          id: "JxtcOM50Qm0e",
          type: "multiple_choice",
          ref: "digitalIntensity",
        },
      },
      {
        type: "choice",
        choice: {
          id: "dsg572gscKgo",
          label: "…*le neuf en priorité* (même si l'occasion est disponible)",
          ref: "84702054-4b2e-40c9-932a-3bd813d5d646",
        },
        field: {
          id: "Dpl4qNCPtGVV",
          type: "multiple_choice",
          ref: "purchasingStrategy",
        },
      },
      {
        type: "choice",
        choice: {
          id: "TJaIV97Vek20",
          label: "*0*",
          ref: "22c056f4-21e7-4e63-8fb6-60b1f5569f8b",
        },
        field: {
          id: "HreBEMDifVhr",
          type: "multiple_choice",
          ref: "airTravelFrequency",
        },
      },
      {
        type: "choice",
        choice: {
          id: "pt9lOL1L8zvk",
          label: "*Électricité, réseau de chaleur ou pompe à chaleur*",
          ref: "6a3d2558-6612-4cf1-90a6-e5e1bf3bbca8",
        },
        field: {
          id: "rOBkR1gVgkyP",
          type: "multiple_choice",
          ref: "heatSource",
        },
      },
      {
        type: "email",
        email: "an_account@example.com",
        field: {
          id: "wldBg2PVYBgI",
          type: "email",
          ref: "email",
        },
      },
    ],
    ending: {
      id: "OEYROGkSgGg3",
      ref: "9acf61d6-becd-4a62-bea3-4353c07d5769",
    },
  },
};
