import { BroadcastChannel, type CarbonFootprintAnswer } from "@prisma/client";
import { faker } from "@faker-js/faker";
import { type BuilderCarbonFootprintAnswer } from "~/types/CarbonFootprint";

export const buildCarbonFootprintAnswer = (
  surveyId: number,
  suId: number,
  data?: Partial<CarbonFootprintAnswer>,
): BuilderCarbonFootprintAnswer => ({
  emailApiCalled: false,
  broadcastChannel: faker.helpers.arrayElement(Object.values(BroadcastChannel)),
  email: Date.now() + faker.internet.email(),
  globalNote: faker.number.float(),
  transportation: faker.number.float(),
  transportationCar: faker.number.float(),
  transportationCarKm2: faker.lorem.word(),
  transportationCarOilConsumption100: faker.lorem.word(),
  transportationCarOilType: faker.lorem.word(),
  transportationCarElectricConsumption100: faker.lorem.word(),
  transportationPlane: faker.number.float(),
  transportationBicycle: faker.number.float(),
  transportationSoftMobility: faker.number.float(),
  transportationTrain: faker.number.float(),
  transportationPublicTransport: faker.number.float(),
  transportationCarLongDistance: faker.lorem.word(),
  transportationHollidays: faker.number.float(),
  transportationHollidaysCaravan: faker.lorem.word(),
  transportationHollidaysCampingCar: faker.lorem.word(),
  transportationHollidaysVan: faker.lorem.word(),
  transportationHollidaysRentalVehicle: faker.lorem.word(),
  transportationHollidaysCruise: faker.lorem.word(),
  transportationFerry: faker.number.float(),
  alimentation: faker.number.float(),
  alimentationMeals: faker.number.float(),
  alimentationLunchDinner: faker.number.float(),
  alimentationBonus: faker.number.float(),
  alimentationLocalImpact: faker.number.float(),
  alimentationLocalConsumption: faker.lorem.word(),
  alimentationSeasonalImpact: faker.number.float(),
  alimentationAnnualBreakfast: faker.number.float(),
  alimentationDeforestation: faker.number.float(),
  alimentationDrinks: faker.number.float(),
  alimentationHotDrinks: faker.number.float(),
  alimentationColdDrinks: faker.number.float(),
  alimentationWaste: faker.number.float(),
  alimentationWasteHabits: faker.lorem.word(),
  logement: faker.number.float(),
  logementConstruction: faker.number.float(),
  logementConstructionBase: faker.number.float(),
  logementConstructionCooling: faker.number.float(),
  logementConstructionRenovation: faker.number.float(),
  logementConstructionDeforestation: faker.number.float(),
  logementConstructionSoilArtificialization: faker.lorem.word(),
  logementElectricity: faker.number.float(),
  logementElectricityTotalConsumption: faker.number.float(),
  logementElectricitySolarAutoconsumption: faker.lorem.word(),
  logementElectricityCarbonIntensity: faker.number.float(),
  logementHeating: faker.number.float(),
  logementAirConditioning: faker.number.float(),
  logementSwimmingPool: faker.lorem.word(),
  logementOutdor: faker.number.float(),
  logementHollidays: faker.number.float(),
  logementHollidaysHotelImpact: faker.lorem.word(),
  logementHollidaysCampingImpact: faker.lorem.word(),
  logementHollidaysYouthHostelImpact: faker.lorem.word(),
  logementHollidaysRentalImpact: faker.lorem.word(),
  logementHollidaysHomeExchangeImpact: faker.lorem.word(),
  logementHollidaysSecondaryHomeImpact: faker.lorem.word(),
  divers: faker.number.float(),
  diversHouseholdAppliances: faker.number.float(),
  diversHouseholdAppliancesDevices: faker.number.float(),
  diversFurniture: faker.number.float(),
  diversFurnitureItems: faker.number.float(),
  diversFurnitureDeforestation: faker.number.float(),
  diversFurniturePreservation: faker.lorem.word(),
  diversDigital: faker.number.float(),
  diversDigitalInternet: faker.number.float(),
  diversDigitalDevices: faker.number.float(),
  diversTextile: faker.number.float(),
  servicesSocietal: faker.number.float(),
  servicesPublics: faker.lorem.word(),
  servicesMarket: faker.lorem.word(),
  answers: { anything: "ok" },

  ...data,
  surveyId,
  suId,
});
