import { BroadcastChannel, type CarbonFootprintAnswer } from "@prisma/client";
import { faker } from "@faker-js/faker";
import { type BuilderCarbonFootprintAnswer } from "~/types/CarbonFootprint";

const kg = (min: number, max: number) => faker.number.float({ min, max });

export const buildCarbonFootprintAnswer = (
  surveyId: number,
  data?: Partial<CarbonFootprintAnswer>,
): BuilderCarbonFootprintAnswer => ({
  broadcastChannel: faker.helpers.arrayElement(Object.values(BroadcastChannel)),
  broadcastId: faker.string.uuid(),
  externalId: faker.string.uuid(),
  email: Date.now() + faker.internet.email(),
  globalNote: kg(4000, 12000),
  transportation: kg(20, 900),
  transportationCar: kg(400, 1800),
  transportationCarKm2: kg(20, 900),
  transportationCarOilConsumption100: kg(20, 900),
  transportationCarOilType: faker.string.alphanumeric(),
  transportationCarElectricConsumption100: kg(20, 900),
  transportationPlane: kg(300, 2000),
  transportationBicycle: kg(5, 60),
  transportationSoftMobility: kg(5, 60),
  transportationTrain: kg(20, 200),
  transportationPublicTransport: kg(30, 250),
  transportationCarLongDistance: kg(20, 900),
  transportationHollidays: kg(150, 900),
  transportationHollidaysCaravan: kg(20, 900),
  transportationHollidaysCampingCar: kg(20, 900),
  transportationHollidaysVan: kg(20, 900),
  transportationHollidaysRentalVehicle: kg(20, 900),
  transportationHollidaysCruise: kg(20, 900),
  transportationFerry: kg(10, 150),
  alimentation: kg(20, 900),
  alimentationMeals: kg(20, 900),
  alimentationLunchDinner: kg(500, 1600),
  alimentationBonus: kg(20, 900),
  alimentationLocalImpact: kg(20, 900),
  alimentationLocalConsumption: faker.string.alphanumeric(),
  alimentationSeasonalImpact: kg(20, 900),
  alimentationAnnualBreakfast: kg(50, 250),
  alimentationDeforestation: kg(80, 400),
  alimentationDrinks: kg(50, 300),
  alimentationHotDrinks: kg(20, 900),
  alimentationColdDrinks: kg(20, 900),
  alimentationWaste: kg(30, 200),
  alimentationWasteHabits: kg(20, 900),
  logement: kg(20, 900),
  logementConstruction: kg(300, 1200),
  logementConstructionBase: kg(20, 900),
  logementConstructionCooling: kg(20, 900),
  logementConstructionRenovation: kg(20, 900),
  logementConstructionDeforestation: kg(20, 900),
  logementConstructionSoilArtificialization: kg(20, 900),
  logementElectricity: kg(150, 700),
  logementElectricityTotalConsumption: kg(20, 900),
  logementElectricitySolarAutoconsumption: kg(20, 900),
  logementElectricityCarbonIntensity: kg(20, 900),
  logementHeating: kg(400, 1800),
  logementAirConditioning: kg(10, 150),
  logementSwimmingPool: kg(0, 250),
  logementOutdor: kg(10, 100),
  logementHollidays: kg(50, 350),
  logementHollidaysHotelImpact: kg(20, 900),
  logementHollidaysCampingImpact: kg(20, 900),
  logementHollidaysYouthHostelImpact: kg(20, 900),
  logementHollidaysRentalImpact: kg(20, 900),
  logementHollidaysHomeExchangeImpact: kg(20, 900),
  logementHollidaysSecondaryHomeImpact: kg(20, 900),
  divers: kg(20, 900),
  diversHouseholdAppliances: kg(50, 300),
  diversHouseholdAppliancesDevices: kg(20, 900),
  diversFurniture: kg(80, 400),
  diversFurnitureItems: kg(20, 900),
  diversFurnitureDeforestation: kg(20, 900),
  diversFurniturePreservation: faker.string.alphanumeric(),
  diversDigital: kg(20, 900),
  diversDigitalInternet: kg(20, 150),
  diversDigitalDevices: kg(100, 500),
  diversTextile: kg(50, 300),
  servicesSocietal: kg(20, 900),
  servicesPublics: kg(150, 600),
  servicesMarket: kg(150, 600),
  answers: { anything: "ok" },

  airTravelFrequency: null,
  digitalIntensity: null,
  heatSource: null,
  meatFrequency: null,
  purchasingStrategy: null,
  transportationMode: null,

  distanceToBarycenter: null,
  knowSu: true,

  ...data,
  surveyId,
});
