import { type SuBankData } from "~/types/Dataviz";

export const buildSuBank = (data: Partial<SuBankData> & { id: number }): SuBankData => ({
  name: `su-bank-${data.id}`,
  icon1: "",
  icon2: "",
  ornement: "",
  background: "",
  colorMain: "#000000",
  colorDark1: "",
  colorDark2: "",
  colorDark3: "",
  colorDark4: "",
  colorDark5: "",
  colorLight1: "",
  colorLight2: "",
  colorLight3: "",
  colorLight4: "",
  colorLight5: "",
  colorComp1: "",
  colorComp2: "",
  colorGraph1: "",
  colorGraph2: "",
  colorGraph3: "",
  colorGraph4: "",
  colorGraph5: "",
  colorGraph6: "",
  colorGraph7: "",
  colorGraph8: "",
  colorGraph9: "",
  colorGraph10: "",
  position: "",
  icon1Link: "",
  icon1Source: "",
  icon1Attribution: "",
  icon2Link: "",
  icon2Source: "",
  icon2Attribution: "",
  ornementLink: "",
  ornementSource: "",
  ornementAttribution: "",
  backgroundBin: "",
  backgroundFilepath: "",
  backgroundLink: "",
  backgroundSource: "",
  ...data,
});
