import { BroadcastChannel, type CarbonFootprintAnswer } from "@prisma/client";
import { z } from "zod";

export const NgcWebhookSchema = z.object({
  id: z.string(),
  broadcastChannel: z.nativeEnum(BroadcastChannel),
  neighborhood: z.string(), // near-47 to confirm it is in body
  suId: z.number(), // near-47 to confirm it is in body
  email: z.string().email().or(z.literal("")).optional().nullable(), // near-47 to confirm it is in body
  calculatedResults: z.object({
    bilan: z.number(),
    transport: z.number(),
    "transport . voiture": z.number(),
    "transport . voiture . km2": z.string().optional(),
    "transport . voiture . thermique . consommation aux 100": z
      .string()
      .optional(),
    "transport . voiture . thermique . carburant": z.string().optional(),
    "transport . voiture . électrique . consommation aux 100": z
      .string()
      .optional(),
    "transport . avion": z.number(),
    "transport . deux roues": z.number(),
    "transport . mobilité douce": z.number(),
    "transport . train": z.number(),
    "transport . transports commun": z.number(),
    "transport . car longue distance": z.string().optional(),
    "transport . vacances": z.number(),
    "transport . vacances . caravane": z.string().optional(),
    "transport . vacances . camping car": z.string().optional(),
    "transport . vacances . van": z.string().optional(),
    "transport . vacances . location véhicule ": z.string().optional(),
    "transport . vacances . croisière": z.string().optional(),
    "transport . ferry": z.number(),
    alimentation: z.number(),
    "alimentation . repas": z.number(),
    "alimentation . déjeuner et dîner": z.number(),
    "alimentation . bonus": z.number(),
    "alimentation . local . empreinte": z.number(),
    "alimentation . local . consommation": z.string(),
    "alimentation . de saison . empreinte": z.number(),
    "alimentation . petit déjeuner annuel": z.number(),
    "alimentation . déforestation": z.number(),
    "alimentation . boisson": z.number(),
    "alimentation . boisson . chaude": z.number(),
    "alimentation . boisson . froide": z.number(),
    "alimentation . déchets": z.number(),
    "alimentation . déchets . gestes": z.string().optional(),
    logement: z.number(),
    "logement . construction": z.number(),
    "logement . construction . base": z.number(),
    "logement . construction . rafraichissement": z.number(),
    "logement . construction . rénovation": z.number(),
    "logement . construction . déforestation": z.number(),
    "logement . construction . artificialisation sols": z.string().optional(),
    "logement . électricité": z.number(),
    "logement . électricité . consommation totale": z.number(),
    "logement . électricité . photovoltaique . autoconsommation": z
      .string()
      .optional(),
    "logement . électricité . intensité carbone équivalente": z.number(),
    "logement . chauffage": z.number(),
    "logement . climatisation": z.number(),
    "logement . piscine": z.string().optional(),
    "logement . extérieur": z.number(),
    "logement . vacances": z.number(),
    "logement . vacances . empreinte hotel": z.string().optional(),
    "logement . vacances . empreinte camping": z.string().optional(),
    "logement . vacances . empreinte auberge de jeunesse": z
      .string()
      .optional(),
    "logement . vacances . empreinte locations": z.string().optional(),
    "logement . vacances . empreinte échange": z.string().optional(),
    "logement . vacances . empreinte résidence secondaire": z
      .string()
      .optional(),
    divers: z.number(),
    "divers . électroménager": z.number(),
    "divers . électroménager . appareils": z.number(),
    "divers . ameublement": z.number(),
    "divers . ameublement . meubles": z.number(),
    "divers . ameublement . déforestation": z.number(),
    "divers . ameublement . préservation": z.string(),
    "divers . numérique": z.number(),
    "divers . numérique . internet": z.number(),
    "divers . numérique . appareils": z.number(),
    "divers . textile": z.number(),
    "services sociétaux": z.number(),
    "services publics": z.string().optional(),
    "services marchands": z.string().optional(),
  }),
  answers: z.record(z.any()),
});

export type NgcWebhookPayload = z.infer<typeof NgcWebhookSchema>;

export const convertedCarbonFootprintAnswer = z.object({
  email: z.string().email().or(z.literal("")).optional().nullable(),
  broadcastChannel: z.nativeEnum(BroadcastChannel),
  globalNote: z.number(),
  transportation: z.number(),
  transportationCar: z.number(),
  transportationCarKm2: z.string().optional(),
  transportationCarOilConsumption100: z.string().optional(),
  transportationCarOilType: z.string().optional(),
  transportationCarElectricConsumption100: z.string().optional(),
  transportationPlane: z.number(),
  transportationBicycle: z.number(),
  transportationSoftMobility: z.number(),
  transportationTrain: z.number(),
  transportationPublicTransport: z.number(),
  transportationCarLongDistance: z.string().optional(),
  transportationHollidays: z.number(),
  transportationHollidaysCaravan: z.string().optional(),
  transportationHollidaysCampingCar: z.string().optional(),
  transportationHollidaysVan: z.string().optional(),
  transportationHollidaysRentalVehicle: z.string().optional(),
  transportationHollidaysCruise: z.string().optional(),
  transportationFerry: z.number(),
  alimentation: z.number(),
  alimentationMeals: z.number(),
  alimentationLunchDinner: z.number(),
  alimentationBonus: z.number(),
  alimentationLocalImpact: z.number(),
  alimentationLocalConsumption: z.string().optional(),
  alimentationSeasonalImpact: z.number(),
  alimentationAnnualBreakfast: z.number(),
  alimentationDeforestation: z.number(),
  alimentationDrinks: z.number(),
  alimentationHotDrinks: z.number(),
  alimentationColdDrinks: z.number(),
  alimentationWaste: z.number(),
  alimentationWasteHabits: z.string().optional(),
  logement: z.number(),
  logementConstruction: z.number(),
  logementConstructionBase: z.number(),
  logementConstructionCooling: z.number(),
  logementConstructionRenovation: z.number(),
  logementConstructionDeforestation: z.number(),
  logementConstructionSoilArtificialization: z.string().optional(),
  logementElectricity: z.number(),
  logementElectricityTotalConsumption: z.number(),
  logementElectricitySolarAutoconsumption: z.string().optional(),
  logementElectricityCarbonIntensity: z.number(),
  logementHeating: z.number(),
  logementAirConditioning: z.number(),
  logementSwimmingPool: z.string().optional(),
  logementOutdor: z.number(),
  logementHollidays: z.number(),
  logementHollidaysHotelImpact: z.string().optional(),
  logementHollidaysCampingImpact: z.string().optional(),
  logementHollidaysYouthHostelImpact: z.string().optional(),
  logementHollidaysRentalImpact: z.string().optional(),
  logementHollidaysHomeExchangeImpact: z.string().optional(),
  logementHollidaysSecondaryHomeImpact: z.string().optional(),
  divers: z.number(),
  diversHouseholdAppliances: z.number(),
  diversHouseholdAppliancesDevices: z.number(),
  diversFurniture: z.number(),
  diversFurnitureItems: z.number(),
  diversFurnitureDeforestation: z.number(),
  diversFurniturePreservation: z.string().optional(),
  diversDigital: z.number(),
  diversDigitalInternet: z.number(),
  diversDigitalDevices: z.number(),
  diversTextile: z.number(),
  servicesSocietal: z.number(),
  servicesPublics: z.string().optional(),
  servicesMarket: z.string().optional(),
  suId: z.number(),
  answers: z.record(z.any()),
});

export type ConvertedCarbonFootprintAnswer = z.infer<
  typeof convertedCarbonFootprintAnswer
>;

export type BuilderCarbonFootprintAnswer = Omit<
  CarbonFootprintAnswer,
  "id" | "createdAt" | "updatedAt" | "su" | "suId"
> &
  Partial<
    Pick<CarbonFootprintAnswer, "id" | "createdAt" | "updatedAt" | "suId">
  >;
