export enum CategoryLabels {
  man = "d'hommes",
  woman = "de femmes",
  above_75 = "de personnes de plus de 75 ans",
  from_60_to_74 = "de personnes entre 60 et 74 ans",
  from_45_to_59 = "de personnes entre 45 et 59 ans",
  from_30_to_44 = "de personnes entre 30 et 44 ans",
  from_15_to_29 = "de personnes entre 15 et 29 ans",
  cs1 = "d'agriculteurs exploitants (CS1)",
  cs2 = "d'artisans, commerçants, chefs d'entreprise (CS2)",
  cs3 = "de cadres et Professions intellectuelles supérieures (CS3)",
  cs4 = "de professions intermédiaires",
  cs5 = "d'employés",
  cs6 = "d'ouvriers",
  cs7 = "de retraités",
  cs8 = "de personnes dans la catégorie autres ou sans activité professionnelle",
}
