export enum CategoryLabels {
  man = "Hommes",
  woman = "Femmes",
  above_75 = "Personnes de plus de 75 ans",
  from_60_to_74 = "Personnes entre 60 et 74 ans",
  from_45_to_59 = "Personnes entre 45 et 59 ans",
  from_30_to_44 = "Personnes entre 30 et 44 ans",
  from_15_to_29 = "Personnes entre 15 et 29 ans",
  cs1 = "Agriculteurs exploitants",
  cs2 = "Artisans, commerçants, chefs d'entreprise",
  cs3 = "Cadres et Professions intellectuelles supérieures",
  cs4 = "Professions intermédiaires",
  cs5 = "Employés",
  cs6 = "Ouvriers",
  cs7 = "Retraités",
  cs8 = "Personnes dans la catégorie autres ou sans activité professionnelle",
}
