name: Flask api tests

on:
  pull_request:
    branches: [develop]
    paths:
      - 'api-su/**'

defaults:
  run:
    working-directory: ./api-su

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pipx install pipenv

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pipenv"

      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: pipenv install --dev
      
      - name: Run tests
        run: pipenv run test
